project:
  type: book
  output-dir: docs

book:
  title: "Effiziente Nutzung knapper Ressourcen"
  author: "Prof. Dr. Jan S. Voßwinkel"
  # date: "2025"
  subtitle: "Sommersemester 2025"
  #lang: de
  language:  _language.yml
  repo-url: https://github.com/janvoss/Effizienz.git
#  issued: "Sommersemester 2024"
  license: "CC BY-SA"
  chapters:
    - index.qmd
    - intro.qmd
    - Zukunft.qmd
    - Bedeutung.qmd # individuell vs sozial 
    - Wissenschaftstheorie.qmd
    - Modelle-Rationalitaet.qmd
    - Intertemporal.qmd
    - Spieltheorie.qmd
    - Maerkte.qmd
    - Marktversagen.qmd
    - BIP.qmd
    - Geld.qmd
    - Handel.qmd
    - Ausblick.qmd
    - literatur.qmd
    - Uebungsaufgaben.qmd 




bibliography: Effizienz.bib



format:
  html:
    theme: cosmo
    code-fold: true
    code-overflow: wrap

editor: source

