# Effizienz und Rationalität 

## Soziale Phänomene

- Soziale Phänomene entstehen durch Entscheidungen und Interaktion von Individuen. 

- Sie sind regelmäßig  	&bdquo;Ergebnis menschlichen Handelns aber nicht menschlichen Entwurfs&ldquo; (Hayek) (**spontane Ordnung**)

## Gleichgewichte

- Ein Gleichgewicht liegt vor, wenn ein System ohne &bdquo;Störungen&ldquo;  durch äußere Einflüsse in Ruhe verbleibt. 

- Muster: Individuelle Entscheidungen $\rightarrow$ Interaktion/Anpassung/Aggregation $\rightarrow$ Gleichgewicht. Exogener Schock $\rightarrow$ neue individuelle Entscheidungen $\rightarrow$ Interaktion/Anpassung/Aggregation $\rightarrow  \dots$

## Erklärungen durch Modelle

(wissenschaftliche) **Erklärung**: Antwort auf eine Warum-Frage unter Rückgriff auf systematische Zusammenhänge

**Theorie**: Systematische Vorstellung über Aspekte der Welt

**Modell**: Theoriegeleitetes Abbild einer Situation


**Modellgestützte Erklärung**: 

- **Systematischer Zusammenhang** zwischen unabhängigen und abhängigen Variablen.

- Erlaubt die Formulierung einer **Erwartung** über Entwicklung der abhängigen Variable in Abhängigkeit von der Entwicklung der unabhängigen Variable. 

- Erlaubt **keine** Prognose von Einzelereignissen

- In jedem **Einzelfall** wirkt eine **Vielzahl von unsystematischen Einzelfaktoren**, die sich nicht systematisch erklären lassen. 



```{r Modell-Stoerung, echo=F, warning=F, message=F, cache=F}
library(tidyverse)

# df erzeugen
set.seed(123)

index <- 1:100

df <- as.data.frame(index) %>% 
  mutate(trend = .2*index^2+30,
         beobachtung = trend+rnorm(100, 0, 150))

#(Zusätzlicher df, um vertikale Linien in Grafik zu erzeugen, s. https://stackoverflow.com/questions/12253239/vertical-lines-between-points-with-ggplot2)

trend1 <- df$trend
beobachtung1 <- df$beobachtung
index1 <- rep(1:100,2)

df1 <- data.frame(index1=index1,
                 y=c(trend1, beobachtung1))

# Bild erzeugen

p <- df %>% 
  ggplot(aes(index, beobachtung))+
  geom_point(aes(color="Beobachtungen"))+
#  geom_line()+
  geom_line(aes(x=index1, y=y, group=df1$index1, color="zufällige Störungen"), data=df1)+
  geom_line(aes(y=trend, color= "Erklärung"))+
  scale_color_manual(values=c("blue", "red", "gray"))+
  scale_x_continuous(breaks= NULL) +
  scale_y_continuous(breaks= NULL) +
  theme_classic()+
  theme(panel.grid = element_blank()) +
  theme(axis.line = element_line(arrow = arrow(type='closed', length = unit(5,'pt'))))+
  labs(title="Erklärung und Zufall",
       caption="Darstellung: Jan S. Voßwinkel",
    x = "unabhängige Variable", y = "abhängige Variable", 
       color="",
       fill="")

p

```


- Modelle erlauben es, den Grad an Komplexität zu steuern. 
  - Beschränkung (zunächst) auf Zusammenhänge, von denen man annimmt, dass sie stark sind  
  - dann ggf sukzessive Aufnahme weiterer Zusammenhänge

## Individuelles vs. gesellschaftliches Entscheidungsproblem

### Individuelles Entscheidungsproblem

Das Folgende ist fast wörtlich aus @detel_grundkurs_2007 S. 20 übernommen.

## Basisschema der Handlungserklärung

1. Person $S$ wünscht, Ziel $Z$ zu realisieren.

2. $S$ glaubt, die Handlung $H$ sei ein Mittel, um $Z$ zu realisieren.

3. **$S$ vollzieht Handlung $H$**.


Das Basisschema ist noch unvollständig:

- Was ist, wenn es für $S$ bessere Handlungen als $H$ gibt, $Z$ zu
realisieren? Dann wäre es nicht vernünftig, $H$ zu vollziehen.
-  Was ist, wenn es $S$ $H$ gar nicht vollziehen kann?
-  Was ist, wenn $H$ mit negativen Folgen einhergeht, die schlimmer
sind, als $Z$ nicht zu realisieren?
-  Was ist, wenn $S$ noch weitere Ziele realisieren will, die mit $Z$
nicht vereinbar sind?

$\Rightarrow$ **erweitertes Schema der Handlungserklärung**


## Erweitertes Schema der Handlungserklärung

1. $S$ hat die Absicht, Ziel $Z$ zu realisieren.

2. $S$ glaubt, dass, wenn sie Handlung $H$ vollzieht, sie somit $Z$
realisieren kann.

3. $S$ glaubt in der Lage zu sein, $Z$ zu realisieren und $H$ zu vollziehen.

4. $S$ weiß, wie man $Z$ realisiert und $H$ vollzieht.

4. $S$ glaubt nicht, dass es etwas Besseres gibt als $H$, um $Z$ zu
realisieren.

5. $S$ glaubt nicht, dass der Vollzug von $H$ Folgen hat, die schlimmer
sind als nicht $Z$ realisieren zu können.

6. $S$ hat nicht die Absicht, ein Ziel zu realisieren, von dem $S$
weiß, dass es unvereinbar damit ist, $Z$ zu realisieren, und das
sie $Z$ gegenüber vorzieht.

7. **$S$ vollzieht Handlung $H$.**

## Zwischenfazit

- Erklärungen rationaler Handlungen unterstellen nicht zwangsläufig,
dass die handelnde Person "alles richtig"  macht. 
-  Insbesondere lässt es beschränkte Handlungsmöglichkeiten zu und unvollständige
oder fehlerhafte Informationslagen.
- Das **Rationalprinzip** ist weniger eine Behauptung über die handelnde
Person, sondern ein Schema, eine **"Grammatik" der Erklärung**.

- Diese Grammatik verwenden wir sowohl in der Spieltheorie als auch in der Verhaltensökonomik  
  - Schwerpunkt **Spieltheorie**: Individuen handeln nach (dem richtigen) mathematischen Kalkül und machen höchstens zufällig Fehler  
  - Schwerpunkt **Verhaltensökonomik**: Individuen handeln nachvollziehbar, aber nach Kalkülen, die nicht ganz "richtig" sind.


[Maximierung einer Nutzenfunktion]::

### Gesellschaftliches Entscheidungsproblem

#### Pareto-Verbesserungen und Pareto-Effizienz

[Edgeworth]::

[Hier auch potenzielle Pareto-Verbesserungen]::

#### Auswahl zwischen verschiedenen effizienten Zuständen
