# Die ökonomische Analyse sozialer Phänomene

## Soziale Phänomene und individuelles Handeln

- Soziale Phänomene entstehen durch Entscheidungen und Interaktion von Individuen. 

- Sie sind regelmäßig  	&bdquo;Ergebnis menschlichen Handelns aber nicht menschlichen Entwurfs&ldquo; (Hayek) (**spontane Ordnung**)

## Gleichgewichte

- Ein Gleichgewicht liegt vor, wenn ein System ohne &bdquo;Störungen&ldquo;  durch äußere Einflüsse in Ruhe verbleibt. 

[Kasten mit ausführlicher Erläuterung?]::

- Muster: Individuelle Entscheidungen $\rightarrow$ Interaktion/Anpassung/Aggregation $\rightarrow$ Gleichgewicht. Exogener Schock $\rightarrow$ neue individuelle Entscheidungen $\rightarrow$ Interaktion/Anpassung/Aggregation $\rightarrow  \dots$

## Erklärungen durch Modelle

(wissenschaftliche) **Erklärung**: Antwort auf eine Warum-Frage unter Rückgriff auf systematische Zusammenhänge

**Theorie**: Systematische Vorstellung über Aspekte der Welt

**Modell**: Theoriegeleitetes Abbild einer Situation


**Modellgestützte Erklärung**: 

- **Systematischer Zusammenhang** zwischen unabhängigen und abhängigen Variablen.

- Erlaubt die Formulierung einer **Erwartung** über Entwicklung der abhängigen Variable in Abhängigkeit von der Entwicklung der unabhängigen Variable(n). 

- **Komplexität** des Modells **steuerbar**  
$\rightarrow$ möglichst **einfache Modelle** verwenden

- Fokussierung auf **interessante Zusammenhänge**

- Erlaubt **keine** Prognose von **Einzel**ereignissen

- In jedem **Einzelfall** wirkt eine **Vielzahl von unsystematischen Einzelfaktoren**, die sich nicht systematisch erklären lassen. 



```{r Modell-Stoerung, echo=F, warning=F, message=F, cache=F}
library(tidyverse)

set.seed(77)

df <- data.frame(x = 0:100) %>%
  mutate(y = exp(x)^.02,
         obs = y + rnorm(n = n(), mean = 0, sd = .5))

model <- df %>% lm(obs ~ x + I(x^2), .)
df$fit <- fitted(model)

ggplot(df, aes(x, obs)) +
  geom_point(aes(color = "Beobachtungen")) +
  geom_line(aes(y = fit, color = "Erklärter Zusammenhang")) +
  geom_segment(aes(x = x, xend = x, y = obs, yend = fit, color = "Unerklärter Rest"), alpha = 0.5) +
  scale_color_manual(values = c("Beobachtungen" = "black", "Erklärter Zusammenhang" = "blue", "Unerklärter Rest" = "red")) +
  scale_x_continuous(breaks=NULL)+
  scale_y_continuous(breaks=NULL)+
  labs(title= "Erklärter und unerklärter Teil von Bebachtungen",
      x= "Unabhängige Variable",
      y= "Abhängige Variable",
      color = "",
      caption="Darstellung: Jan S. Voßwinkel") +
  theme_light()+
  theme(legend.position = "bottom")
```


- Modelle erlauben es, den Grad an Komplexität zu steuern. 
  - Beschränkung (zunächst) auf Zusammenhänge, von denen man annimmt, dass sie stark sind  
  - dann ggf sukzessive Aufnahme weiterer Zusammenhänge

## Typische Grundannahmen in ökonomischen Modellen

- **Methodologischer Individualismus**   	&bdquo;[A]lle sozialen Phänomene, insbesondere das Funktionieren der sozialen Institutionen [sollten] immer als das Resultat der Entscheidungen, Handlungen, Einstellungen menschlicher Individuen verstanden werden und (...) wir [dürfen] nie mit einer Erklärung aufgrund sogenannter 'Kollektive' (Staaten, Nationen, Rassen usw.) zufrieden sein.&ldquo; (Karl Popper 1992, S. 116)

- **Normativer Individualismus **Die Ziele keines einzigen Menschen sind a priori wichtiger als die irgendeines anderen Menschen. Ausschließlich Individuen und alle Individuen sind Quelle von Werten.

- **Rationalität** der handelnden Subjekte wird unterstellt (Verknüpfung
von Situation und Handlung möglich)

- **Präferenzen** werden als **gegeben** angenommen 

- **Veränderliche Restriktionen** bestimmen folglich Ergebnisse


## Twitter-Universität: Methodologischer Individualismus und sonstigen Annahmen in der Ökonomik {-}

<blockquote class="twitter-tweet" data-dnt="true"><p lang="de" dir="ltr">Wie kann das sein? Die „Mainstream“-Ökonomie beschäftigt sich seit Jahren mit Fragen von Marktmacht und Einflussnahme. Vorschläge zu wirksamem Klimaschutz, die auf einer Analyse der Anreize und Machtverhältnisse basieren, werden seit Jahren nicht oder nur halbherzig umgesetzt. <a href="https://t.co/xxRjN3FgUy">https://t.co/xxRjN3FgUy</a></p>&mdash; Veronika Grimm (@GrimmVeronika) <a href="https://twitter.com/GrimmVeronika/status/1641749578754957313?ref_src=twsrc%5Etfw">March 31, 2023</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>    
